:api_key: 0c037a6ea6ec0eac179e26c4b942dc60
:password: b6217ccc181717bb1f17145f0421abaf
:theme_id: "7"
:preview_url: https://lojatemavestvertex.commercesuite.com.br/loja/loja.php?loja=1114294&opencode_theme=62aa0b3a35021
:debug: false
